import { Wind, Brain, Heart, Clock } from "lucide-react";

export const wellnessPrograms = [
  {
    id: 1,
    title: "Deep Breathing Basics",
    description: "Learn fundamental breathing techniques for instant calm",
    duration: "5 min",
    difficulty: "Beginner",
    category: "Breathing",
    icon: Wind,
    color: "bg-blue-500",
    rating: 4.8,
    videoId: "YRPh_GaiL8s",
    instructor: "Dr. Sarah Johnson",
  },
  {
    id: 2,
    title: "Mindful Meditation",
    description: "Guided meditation for mental clarity and focus",
    duration: "10 min",
    difficulty: "Intermediate",
    category: "Meditation",
    icon: Brain,
    color: "bg-purple-500",
    rating: 4.9,
    videoId: "inpok4MKVLM",
    instructor: "Dr. Michael Chen",
  },
  {
    id: 3,
    title: "Progressive Muscle Relaxation",
    description: "Release physical tension throughout your body",
    duration: "15 min",
    difficulty: "Beginner",
    category: "Relaxation",
    icon: Heart,
    color: "bg-pink-500",
    rating: 4.7,
    videoId: "86HUcX8ZtAk",
    instructor: "Dr. Lisa Martinez",
  },
  {
    id: 4,
    title: "Stress Relief Visualization",
    description: "Mental imagery techniques for stress reduction",
    duration: "12 min",
    difficulty: "Intermediate",
    category: "Visualization",
    icon: Brain,
    color: "bg-green-500",
    rating: 4.6,
    videoId: "ZToicYcHIOU",
    instructor: "Dr. Amanda White",
  },
  {
    id: 5,
    title: "Quick Energy Boost",
    description: "Energizing breathing exercises for mental alertness",
    duration: "3 min",
    difficulty: "Beginner",
    category: "Energy",
    icon: Wind,
    color: "bg-orange-500",
    rating: 4.5,
    videoId: "tybOi4hjZFQ",
    instructor: "Dr. James Wilson",
  },
  {
    id: 6,
    title: "Sleep Preparation",
    description: "Calming techniques to prepare for restful sleep",
    duration: "20 min",
    difficulty: "Beginner",
    category: "Sleep",
    icon: Heart,
    color: "bg-indigo-500",
    rating: 4.8,
    videoId: "aXItOY0sLRY",
    instructor: "Dr. Rachel Davis",
  },
  {
    id: 7,
    title: "Countdown Test Video",
    description: "Test session using the countdown video",
    duration: "5 sec",
    difficulty: "Beginner",
    category: "Test",
    icon: Clock,
    color: "bg-gray-500",
    rating: 5.0,
    videoId: "icPHcK_cCF4",
    instructor: "Test Instructor",
  },
];
